[project]
name = "netcalc"
version = "0.1.0"
description = "A simple personal finance app to track transactions and calculate savings."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "pandas>=2.3.3",
    "py-expression-eval>=0.3.14",
    "requests>=2.32.5",
    "streamlit>=1.52.2",
    "supabase>=2.27.0",
]
